### ISSUE TITLE
[Idea] Time cycle and Day and Night mode

### ISSUE THREAD

**Issue by bonclide** [BricksVR/bricksvr-issue-tracking#240] opened 2021-07-05 21:13 UTC
It would kinda look peaceful if it was like this. Maybe you could do all sorts of fun stuff with it.
this could also fit in with my command idea. #239 
But yeah.

**Comment by d12** [comment] 2021-07-05 21:14
Closing as duplicate of https://github.com/BricksVR/bricksvr-issue-tracking/issues/145

**Closed as completed by d12** 2021-07-05 21:14 UTC
Labels: feature request, untriaged
