### ISSUE TITLE
Block Grouping 

### ISSUE THREAD

**Issue by Ninjakechi** [BricksVR/bricksvr-issue-tracking#191] opened 2021-05-23 01:49 UTC
Being able to "group" blocks together into a single entity

**Comment by d12** [comment] 2021-05-24 15:49
Closing as duplicate of #26. The tldr here is that it's a decent bit of work to get this working well, and there's open UX issues that we haven't come up with good solutions for yet.

The easier solution to this problem is something like #56 where you can go into a workshop mode and make "composite bricks" that are treated as one brick in-game, but are actually composed of many bricks.

**Closed by d12** 2021-05-24 15:49 UTC
Labels: feature request, untriaged
