### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [BricksVR/bricksvr-issue-tracking#255] opened 2021-07-27 20:51 UTC
**Describe the problem**
Players have no ability to play the game without an internet connection.

**Describe the solution you'd like**
An offline mode which once done building allows you to save the room to your device in some file.

**Comment by d12** [comment] 2021-07-28 15:28
Duplicate of #65

**Closed as completed by d12** 2021-07-28 15:28 UTC
Labels: feature request, untriaged
