### ISSUE TITLE
Background Music Randomly Slowing Down

### ISSUE THREAD

**Issue by DavidTheFrikr** [BricksVR/bricksvr-issue-tracking#119] opened 2021-04-06 15:15 UTC
**Describe the bug**
The background music of the game starts to slow down while the rest of the game seems to run fine

**To Reproduce**
Not sure how to reproduce the behavior, opening and closing the Oculus Dash sometimes fixes it but then it comes back on its own randomly. Booting into the game sometimes slows down the music but then quickly the music goes back to full speed

**Expected behaviour**
Expected behavior is for the music to play at normal speed and not suddenly slow down

**Screenshots or Video**
https://drive.google.com/file/d/1DmjdI7NwRx4R7tksatqji6pppTRh4o_x/view?usp=sharing

**Device information:**
Oculus Quest 2 over Oculus Link (PCVR)

**Build version:**
v0.2.3 Rift PCVR

**Additional context**
I went into the settings and unchecked "Enable microphone", and I was screen sharing the app directly to a friend on Discord

**Comment by d12** [comment] 2021-05-13 16:00
I believe this is caused by DSP latency settings https://forum.unity.com/threads/audio-slowing-down-during-runtime.912923/

**Comment by d12** [comment] 2021-05-13 16:12
Should be fixed in v0.2.21 🎉

**Closed** 2021-05-13 20:04 UTC
Labels: bug, medium priority, pcvr
