### ISSUE TITLE
Ability to choose between dark mode and light mode

### ISSUE THREAD

**Issue by ControllerData** [BricksVR/bricksvr-issue-tracking#219] opened 2021-06-17 01:27 UTC
**Describe the problem**
I'd like to burn my eyes in BricksVR

**Describe the solution you'd like**
Toggle between dark mode and light mode

**Additional context**
![1_LoAAKCmLu_m5N5HVXbkUOw](https://user-images.githubusercontent.com/29762615/122316349-b38d0f00-cee9-11eb-9352-b7b25debb0e8.gif)

**Comment by d12** [comment] 2021-07-01 18:35
Duplicate of #59

**Closed by d12** 2021-07-01 18:35 UTC
Labels: feature request, untriaged

**Comment by ATXLtheAxolotl** [comment] 2021-07-30 17:39
> Duplicate of #59

I don’t really think so,
I mean a skybox and different UI modes are different.
