### ISSUE TITLE
A way to pick up builds/build things in your hand.

### ISSUE THREAD

**Issue by EpicPixels654** [BricksVR/bricksvr-issue-tracking#198] opened 2021-05-23 17:30 UTC
I feel like it would be cool to be able to pick up builds you've made. Maybe with a size limit so you don't pick up whole buildings lol. And maybe your player size can affect the size limit

**Comment by d12** [comment] 2021-05-27 13:51
Closing as duplicate of #26

**Closed by d12** 2021-05-27 13:51 UTC
Labels: feature request, untriaged
